id = "jai"
name = "Jai"
version = "0.0.1"
schema_version = 1
authors = ["Aman Tuladhar"]
description = "Jai language support (only highlighting at the moment)"
repository = "https://github.com/amantuladhar/zed-jai"

[grammars.jai]
repository = "https://github.com/amantuladhar/tree-sitter-jai"
commit = "4b1f565b0203cafd15fedde5f642f1d8f6fac5fb"
