id = "jai"
name = "Jai"
version = "0.1.2"
schema_version = 1
authors = ["Aman Tuladhar", "Chip Collier"]
description = "Jai language support"
repository = "https://github.com/amantuladhar/zed-jai"

[language_servers.jails]
name = "jails"
language = "Jai"

[grammars.jai]
# Will replace with 'https://github.com/constantitus/tree-sitter-jai' if PR gets merged
repository = "https://github.com/amantuladhar/tree-sitter-jai"
commit = "e9826985ad7b40fa91544a282909fa8159150d71"
